### ISSUE TITLE
Asking for the licence

### ISSUE THREAD

**Issue by yqshao** [Hartrik/sand-game-js#2]
Hi! And thanks for the cool project! I am interested in learning from your code for a private hobby project, and potentially borrowing some of the code. I hope this is OK, but in case there are certain rules to be followed regarding copying/modifying, may I kindly ask you to add or state the licence for this repo?

**Comment by Hartrik** [comment]
Hi. Thank you for your interest in my project :)

I will think about the proper license. Generally speaking I don't mind using it for educational purposes, derived private hobby projects, GitHub forks... I would also accept good quality pull requests.

But publishing derrived (or my original) work on a web page (or Google Play etc.) in assembled (playable) state – it depends.
For example there is a big difference between:
- Using part of my codebase for building a unique game and place it on a personal site – I would give my blessing in exchange for a link and mention :heavy_check_mark:
- Publishing, hardly-changed, on some of those gaming portals full of ads – :x:

**Comment by yqshao** [comment]
Thanks for the prompt reply! I have in my mind some self-hosted (small) art to be shared with a few, no intention for exposure and certainly not publishing for profit/ads. I'll make sure that mentioning of the original work is included and let you know if I managed; of course, if I got ideas for PR I'll be more than happy to open one :>

**Comment by Hartrik** [comment]
Ok, good luck!
